"""empty message

Revision ID: 845e5d3cdfb2
Revises: 
Create Date: 2025-05-14 07:54:34.817451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845e5d3cdfb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('normal_min', sa.FLOAT(precision=2), nullable=False),
    sa.Column('normal_max', sa.FLOAT(precision=2), nullable=False),
    sa.Column('description', sa.String(length=4096), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('analysis',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('document_path', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_markers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('analysis_id', sa.INTEGER(), nullable=False),
    sa.Column('marker_id', sa.INTEGER(), nullable=False),
    sa.Column('value', sa.FLOAT(precision=2), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], ),
    sa.ForeignKeyConstraint(['marker_id'], ['markers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_markers')
    op.drop_table('analysis')
    op.drop_table('users')
    op.drop_table('markers')
    # ### end Alembic commands ###
